name: Build

on:
  push:
    branches: 
      - develop
  pull_request:

jobs:
  build:
    name: Library Build
    runs-on: macos-12
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run build script
        run: sh ./scripts/build.sh