name: Build

on:
  push:
    branches: 
      - develop
  pull_request:

jobs:
  build:
    name: Library Build
    runs-on: macos-13
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.3.app'
      - name: Run build script
        run: sh ./scripts/build.sh