name: Lint

on:
  push:
    branches: 
      - develop
  pull_request:

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-12
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run
        run: swiftlint --strict