name: PodLint

on:
  push:
    branches: 
      - develop
  pull_request:

jobs:
  lint:
    name: Pod Lib Lint
    runs-on: macos-13
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.3.app'
      - name: Run
        run: pod lib lint